apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: env-injector
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
      - 'namespaces'
      - 'configmap'
    verbs:
      - 'get'
      - 'list'
      - 'patch'
  - apiGroups:
      - 'certificates.k8s.io'
    resources:
      - 'CertificateSigningRequest'
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - 'secret'
    verbs:
      - 'create'
      - 'delete'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - 'MutatingWebhookConfiguration'
    verbs:
      - 'create'
      - 'delete'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: env-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: env-injector
subjects:
  - kind: ServiceAccount
    name: env-injector
    namespace: admin
    
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-injector
  namespace: admin