image: registry.cn-shanghai.aliyuncs.com/cinience/k8s-injector:0.0.2
replicas: 1
environment:
  CLUSTER_NAME: ask-test-01
dnsOptions:
  ndots: 3
#  single-request-reopen:
#  use-vc:
labels:
  "k8s.xx.com/label-foo": bar
annotations:
  "k8s.xx.com/annotation-foo": bar
nodeAffinityTerms: {}
#  - matchExpressions:
#      - key: agentpool
#        operator: In
#        values:
#          - ubuntu18
#          - ubuntu1804
